### ISSUE TITLE
Issue when run the repro.py

### ISSUE THREAD

**Issue by visionbike** [josephsdavid/semg_repro#2]
Hi,

when try to run repro.py, this issue happened:
 
Traceback (most recent call last):
  File "/home/user/projects/sEMG-Hand-Gesture-Classification/repro.py", line 94, in <module>
    model.compile(Ranger(learning_rate=1e-3), loss=loss, metrics=["accuracy"])
  File "/home/user/anaconda3/envs/sEMG-Hand-Gesture-Classification/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 570, in compile
    self.optimizer = self._get_optimizer(optimizer)
  File "/home/user/anaconda3/envs/sEMG-Hand-Gesture-Classification/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 608, in _get_optimizer
    return nest.map_structure(_get_single_optimizer, optimizer)
  File "/home/user/anaconda3/envs/sEMG-Hand-Gesture-Classification/lib/python3.9/site-packages/tensorflow/python/util/nest.py", line 914, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/user/anaconda3/envs/sEMG-Hand-Gesture-Classification/lib/python3.9/site-packages/tensorflow/python/util/nest.py", line 914, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/user/anaconda3/envs/sEMG-Hand-Gesture-Classification/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 599, in _get_single_optimizer
    opt = optimizers.get(opt)
  File "/home/user/anaconda3/envs/sEMG-Hand-Gesture-Classification/lib/python3.9/site-packages/tensorflow/python/keras/optimizers.py", line 131, in get
    raise ValueError(
ValueError: Could not interpret optimizer identifier: <optimizers.lookahead.Lookahead object at 0x7fde286f9e50>

I am using the latest tensorflow-gpu v2.8.0

Thank you

**Comment by visionbike** [comment]
I tried to downgrade tensorflow to version 2.5.0 and supprisingly it work!

**Comment by josephsdavid** [comment]
> I tried to downgrade tensorflow to version 2.5.0 and supprisingly it work!

Awesome! I will build a more specific requirements file tonight :)

**Comment by josephsdavid** [comment]
There we go now we can close and others will not have this issue!
